ak_core:
    resource: "@AKCoreBundle/Resources/config/routing.yml"
    prefix:   /

ak_akopenclass:
    resource: "@AKAkopenclassBundle/Resources/config/routing.yml"
    prefix:   /

oc_platform:
    resource: "@AKAkopenclassBundle/Resources/config/routing.yml"
