services:
    oc_platform.antispam:
        class:     AK\AkopenclassBundle\Antispam\AKAntispam
        arguments:
            - "@mailer"
            - %locale%
            - 50

    oc_platform.email.application_mailer:
        class:     AK\AkopenclassBundle\Email\ApplicationMailer
        arguments:
            - "@mailer"

    oc_platform.doctrine_listener.application_creation:
        class:     AK\AkopenclassBundle\DoctrineListener\ApplicationCreationListener
        arguments:
            - "@oc_platform.email.application_mailer"
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    oc_platform.purger.advert:
        class:     AK\AkopenclassBundle\Purger\AdvertPurger
        arguments:
            - "@doctrine.orm.entity_manager"

    oc_platform.validator.antiflood:                                    # Le nom du service
        class:     AK\AkopenclassBundle\Validator\AntifloodValidator    # La classe du service, ici notre validateur déjà créé
        arguments:                                                      # Les données qu'on injecte au service : la requête et l'EntityManager
            - "@request_stack"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: validator.constraint_validator, alias: oc_platform_antiflood }  # C'est avec l'alias qu'on retrouvera le service